## YAML Template.
---
admin_list_short_urls:
    pattern:   /admin/listShortUrls/{page}
    defaults:  { _controller: VellozziUrlShortenerBundle:Admin:list, page: 1  }
    requirements:
        page:  \d+
admin_search_short_urls:
    pattern:   /admin/search/{search}/{page}
    defaults:  { _controller: VellozziUrlShortenerBundle:Admin:search, page: 1  }
    requirements:
        page:  \d+
admin_ws_add_short_url:
    pattern:   /admin/ws/add/
    defaults:  { _controller: VellozziUrlShortenerBundle:AdminWebService:add }
admin_ws_delete_short_url:
    pattern:   /admin/ws/delete/
    defaults:  { _controller: VellozziUrlShortenerBundle:AdminWebService:delete }    
redirect_short_url:
    pattern:   /r/{tag}
    defaults:  { _controller: VellozziUrlShortenerBundle:Front:redirect }
