<?php

namespace Vellozzi\UrlShortenerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlToTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlToTagRepository extends EntityRepository
{
}
